// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsYyZq4yvQosDy7FBCmKZRCGW3sJPGoSA',
    appId: '1:1021109890304:web:68f994b649e8644255d7e5',
    messagingSenderId: '1021109890304',
    projectId: 'trash-bin-locator-421808',
    authDomain: 'trash-bin-locator-421808.firebaseapp.com',
    storageBucket: 'trash-bin-locator-421808.appspot.com',
    measurementId: 'G-S3146ZVQQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc43FKZkQ3zKgLduf5cTG_ERDbyV45g40',
    appId: '1:1021109890304:android:4a87b063e092657755d7e5',
    messagingSenderId: '1021109890304',
    projectId: 'trash-bin-locator-421808',
    storageBucket: 'trash-bin-locator-421808.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg6hSXkHFGh52JElCwA3JkalILADRZ0F8',
    appId: '1:1021109890304:ios:6a5955170258bf7b55d7e5',
    messagingSenderId: '1021109890304',
    projectId: 'trash-bin-locator-421808',
    storageBucket: 'trash-bin-locator-421808.appspot.com',
    iosBundleId: 'com.example.trashBinLocator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg6hSXkHFGh52JElCwA3JkalILADRZ0F8',
    appId: '1:1021109890304:ios:6a5955170258bf7b55d7e5',
    messagingSenderId: '1021109890304',
    projectId: 'trash-bin-locator-421808',
    storageBucket: 'trash-bin-locator-421808.appspot.com',
    iosBundleId: 'com.example.trashBinLocator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsYyZq4yvQosDy7FBCmKZRCGW3sJPGoSA',
    appId: '1:1021109890304:web:b72c157617d7238955d7e5',
    messagingSenderId: '1021109890304',
    projectId: 'trash-bin-locator-421808',
    authDomain: 'trash-bin-locator-421808.firebaseapp.com',
    storageBucket: 'trash-bin-locator-421808.appspot.com',
    measurementId: 'G-HL7CN07806',
  );
}
